# The base URL for the site.
baseURL = "https://udsea.github.io/"
# The title of the site.
title = "Udbhav"
# Enable Git info › https://gohugo.io/methods/page/gitinfo/
enableGitInfo = true
# The default content language.
defaultContentLanguage = "en"
# Whether the default content language is in a subdirectory.
defaultContentLanguageInSubdir = false
# Whether the site has CJK language (Chinese, Japanese, Korean).
hasCJKLanguage = false
ignoreFiles = [
  '(?i)2019-08-08-text-and-typography',
  '(?i)2019-08-09-getting-started',
]

# Pagination settings.
[pagination]
  pagerSize = 6

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Make sure to include JSON output to support the search functionality.
[outputs]
  home = ["HTML", "RSS", "JSON"]

# Import the theme.
[module]
  [[module.imports]]
    path = "github.com/geekifan/hugo-theme-chirpy"
